version: '3.8'

services:
  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: resource-search-frontend:latest
    container_name: resource-search-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
